## Задача 1

Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):
zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],
ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].
Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy
Полученные значения должны быть равны.
Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков,
а затем с использованием функций из библиотек numpy и pandas.

In [5]:
import numpy as np
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [19]:
cov1 = np.mean(zp*ks) - zp.mean() * ks.mean()
cov1

9157.839999999997

In [20]:
cov2 = np.cov(zp, ks, ddof=0)
cov2

array([[ 3494.64,  9157.84],
       [ 9157.84, 30468.89]])

In [31]:
cor1 = cov2 / (np.std(zp, ddof=0)*np.std(ks, ddof=0))
cor1

array([[0.33866702, 0.88749009],
       [0.88749009, 2.95275283]])

In [30]:
cor2 = np.corrcoef(zp, ks)
cor2

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

## Задача 2

Измерены значения IQ выборки студентов,
обучающихся в местных технических вузах:
131, 125, 115, 122, 131, 115, 107, 99, 125, 111.
Известно, что в генеральной совокупности IQ распределен нормально.
Найдите доверительный интервал для математического ожидания с надежностью 0.95.

In [32]:
IQ = np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])

In [33]:
sigma = np.std(IQ, ddof=1)
sigma

10.54566788359614

In [38]:
import scipy.stats as stats
t = stats.t.ppf(0.05/2, len(IQ))

In [39]:
X = np.mean(IQ)

In [40]:
left = X-t*sigma/np.sqrt(len(IQ))
right = X+t*sigma/np.sqrt(len(IQ))
print(f'Доверительнеый интервал  = [{round(left, 2)}; {round(right, 2)}]')

Доверительнеый интервал  = [125.53; 110.67]


## Задача 3

Известно, что рост футболистов в сборной распределен нормально
с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27,
среднее выборочное составляет 174.2. Найдите доверительный интервал для математического
ожидания с надежностью 0.95.

In [49]:
left = 174.2 - 1.96 * 5 / np.sqrt(27)
right = 174.2 + 1.96 * 5 / np.sqrt(27)
print(f'Доверительный интервал для оценки математического ожидания = [{round(left, 2)}; {round(right, 2)}]')

Доверительный интервал для оценки математического ожидания = [172.31; 176.09]
